### ISSUE TITLE
一点小小的建议

### ISSUE THREAD

**Issue by kmtalexwang** [wangrongwei/omnetpp_primer#1]
1. 把文档迁移到博客上去，不然公式放不上去
2. 不要公开你的私人联系方式，用一个工作email或者QQ

**Comment by wangrongwei** [comment]
- 你指的公式是什么？我在Atom下写的，可以插入latex
- 的确没有考虑到私人联系方式这一点，马上改了

**Comment by kmtalexwang** [comment]
github页面上不能渲染公式

**Comment by wangrongwei** [comment]
这个不影响，最后需要转换成pdf格式

**Comment by kmtalexwang** [comment]
老哥，多Agent体系结构懂吗？

**Comment by wangrongwei** [comment]
啥玩意，说人话

**Comment by kmtalexwang** [comment]
基于多Agent的多无人机协同决策算法仿真平台设计_周昊 这篇文章很有代表性，你读一下，应该和你们结合很紧密

**Comment by wangrongwei** [comment]
哦哦，这一篇以前我看过，他们的重点好像在软件实现上，我们的重点在消息路径和架构上，不过可以借鉴他们里边的一些算法

MaxSin <notifications@github.com> 于2018年8月26日周日 下午8:29写道：

**Comment by wangrongwei** [comment]
你可以下拉一下这个仓库了，里边的latexbook目录下我布局了前两章，有些粗糙，但是框架有了

荣巍 <wangrongwei2014@gmail.com> 于2018年8月26日周日 下午9:07写道：

**Comment by kmtalexwang** [comment]
我瞅瞅啊
